from connection import get_mongo_conn

MONGO_CLIENT = get_mongo_conn()
TEST_DB = MONGO_CLIENT.test
TEST_COLLECTION = TEST_DB.test
PRODUCTION = MONGO_CLIENT.production
EMPLOYEES_COLLECTION = PRODUCTION.employees_collection
AGGREGATION_TEST_DB = MONGO_CLIENT.aggregation_test
UNIVERSITIES_COLLECTION = AGGREGATION_TEST_DB.universities
COURSES_COLLECTION = AGGREGATION_TEST_DB.courses
